[project]
name = "pg-faker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Neil Holloway", email = "neil_holloway@hotmail.co.uk" }
]
requires-python = ">=3.13"
dependencies = [
    "faker>=37.4.2",
    "psycopg[binary]>=3.2.9",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
