name: Run tests
on: [push, pull_request]

jobs:
  run-tests:
    name: python ${{ matrix.postgres-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        postgres-version: ['12', '13', '14', '15', '16', '17']

    services:
      postgres:
        image: postgres:${{ matrix.postgres-version }}
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: uv run pytest src/pg_faker/tests